# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "muckraker"
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Benjamin Jackson"]
  s.date = "2012-01-31"
  s.description = "Simple ruby wrapper around the NYTimes/campaign_cash library, which is itself a simple ruby wrapper around the New York Times Campaign Finance API."
  s.email = "bhjackson@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/muckraker.rb",
    "lib/template.html.erb",
    "muckraker.gemspec",
    "spec/chart_spec.rb",
    "spec/factories.rb",
    "spec/load_spec.rb",
    "spec/spec_helper.rb",
    "spec/top_candidates_spec.rb",
    "spec/top_commitees_spec.rb",
    "spec/top_payees_spec.rb"
  ]
  s.homepage = "http://github.com/benjaminjackson/muckraker"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "Pretty and informative charts using the NYTimes Campaign Finance API"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<campaign_cash>, [">= 2.0.8"])
      s.add_runtime_dependency(%q<titlecase>, [">= 0.1.1"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.3"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
      s.add_runtime_dependency(%q<campaign_cash>, [">= 2.0.8"])
      s.add_runtime_dependency(%q<titlecase>, [">= 0.1.1"])
    else
      s.add_dependency(%q<campaign_cash>, [">= 2.0.8"])
      s.add_dependency(%q<titlecase>, [">= 0.1.1"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
      s.add_dependency(%q<simplecov>, [">= 0"])
      s.add_dependency(%q<campaign_cash>, [">= 2.0.8"])
      s.add_dependency(%q<titlecase>, [">= 0.1.1"])
    end
  else
    s.add_dependency(%q<campaign_cash>, [">= 2.0.8"])
    s.add_dependency(%q<titlecase>, [">= 0.1.1"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
    s.add_dependency(%q<simplecov>, [">= 0"])
    s.add_dependency(%q<campaign_cash>, [">= 2.0.8"])
    s.add_dependency(%q<titlecase>, [">= 0.1.1"])
  end
end

